spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deukgeun?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ci_test
    password: Abcd123@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        new_generator_mappings: true
        dialect: org.hibernate.dialect.MySQL57Dialect

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: kim5288403@gmail.com
    password: glxbfqsristuwjko
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: 127.0.0.1
    port: 6379

  cache:
    type: redis
    redis:
      cache-null-values: true

logging:
  level:
    org:
      springframework:
        security: info
        test:
          context: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


trainer:
  mail:
    email: kim5288403@gmail.com

  license:
    api:
      key: 9f3a63e32b74938b30c507160e9d3b4a646f7536ccbecfbeb36ed73db90a3242
      uri: http://data.kca.kr/api/v1/cq/certificate/check

deukgeun:
  role:
    trainer: trainer
    member: member
  status:
    paymentWaiting: 1

jwt:
  secretKey: deuckgeunproject
  authTokenTime: 1800000
  refreshTokenTime: 1080000

iamPort:
  api:
    key: 6640244608024545
    secret: TGJK7YEsO618StWIkXp0FIUErEzyNp2J3J8bQE9LexDvajoydGIuiZF1fL8BWe1xKZyDNxmbjX2YcHmv

cloud:
  aws:
    s3:
      bucket: deukgeunbucket1
      src: https://deukgeunbucket1.s3.ap-northeast-2.amazonaws.com/
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-2
    credentials:
      accessKey: AKIAR62GP44ZVQBHS7GN
      secretKey: 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